### ISSUE TITLE
Setup Poetry

### ISSUE THREAD

**Issue by AFlachs** [jemappellesami/Python-Checkers-AI#1]
Setup poetry pour ce projet de sorte qu'on puisse le lancer depuis le terminal avec "poetry run..." et que des paramètres permettent de définir quelle IA va être utilisée (ou choisir humain)

**Comment by DiegoRubas** [comment]
On peut mettre 2 arguments pour les deux joueurs pour définir le comportement (IA Minimax/IA MCTS/Joueur humain)
