### ISSUE TITLE
[MCTS] List index out of range

### ISSUE THREAD

**Issue by jemappellesami** [jemappellesami/Python-Checkers-AI#12]
Très rarement, on peut tomber sur cette erreur,  et ça a l'air d'être un noeud qui est une feuille mais qui n'a pas au préalable été détecté comme une feuille

Ou alors juste on a pas encore bien géré le cas où un joueur n'a pas de mouvements possibles et doit passer son tour

![Screenshot_20220420_043006](https://user-images.githubusercontent.com/44751925/164122768-f4dbe9b8-dde1-4085-ad0d-13337a2e9433.png)

**Comment by AFlachs** [comment]
C'est lié à l'issue #9 qui a été résolue dans le main
