### ISSUE TITLE
Boucle infinie MCTS

### ISSUE THREAD

**Issue by jemappellesami** [jemappellesami/Python-Checkers-AI#5]
Une boucle infinie a été remarquée pendant que l'arbre s'étend, arrivé 2 fois sur 2 parties avec MCTS, je sais pas s'il suffit juste d'attendre (j'ai stoppé le programme après 1 minute)

![Screenshot_20220405_151423](https://user-images.githubusercontent.com/44751925/161761996-371530d4-0569-49e6-9830-e931eb42ce5b.png)

**Comment by AFlachs** [comment]
C'est probablement en lien avec le problème de l'issue #6, j'attends pour voir si résoudre celle là aide pour ici.
