### ISSUE TITLE
Régler le endgame

### ISSUE THREAD

**Issue by jemappellesami** [jemappellesami/Python-Checkers-AI#6]
Pour l'instant, le endgame est très mal géré, il n'y a qu'une comparaison entre le nombre de pions, ou une fin de partie si l'un des deux n'a plus de mouvement possible

Endroit dans le code : checkers/board.py/winner(self)

Idée d'amélioration : suivre http://www.ffjd.fr/Web/index.php?page=reglesdujeu

**Comment by AFlachs** [comment]
Fin de partie par match nul implémentée
